main:
  - identifier: "home"
    name: "Home"
    url: "/"
    weight: 1
  - identifier: "posts"
    name: "Posts"
    url: "/posts"
    weight: 2
  - identifier: "about"
    name: "About me"
    url: "/about"
    weight: 3
  # - identifier: "categories"
  #   name: "Categories"
  #   url: "/categories"
  #   weight: 3
  # - identifier: "tags"
  #   name: "Tags"
  #   url: "/tags"
  #   weight: 4
  # - identifier: "donate"
  #   name: "Donate"
  #   url: "#"
  #   weight: 5

# Social Media Configuration
social:
  - identifier: "twitter"
    name: "Twitter"
    url: "#"
    weight: 1
  - identifier: "instagram"
    name: "Instagram"
    url: "#"
    weight: 2
  - identifier: "github"
    name: "GitHub"
    url: "#"
    weight: 3
